/**
 * aiInferenceEngine.js — Client-side AI Inference Engine.
 * Runs classification directly in the browser using Hugging Face and OpenRouter APIs.
 */

import { analyzeTextLocally } from './textDetector.js';
import { getKeys } from './keyManager.js';

const HF_API_BASE = 'https://api-inference.huggingface.co/models';

const MODELS = {
  standard: 'Hello-SimpleAI/chatgpt-detector-roberta',
  pro: 'openai-community/roberta-large-openai-detector'
};

let hfAvailable = null;

async function testHfConnectivity() {
  if (hfAvailable !== null) return hfAvailable;
  try {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 3000);
    const resp = await fetch(`${HF_API_BASE}/${MODELS.standard}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ inputs: 'test' }),
      signal: controller.signal
    });
    clearTimeout(timeout);
    hfAvailable = resp.status !== 0;
    console.log(`[AI Inference] HF API connectivity: ${hfAvailable ? 'OK' : 'FAILED'} (status ${resp.status})`);
    return hfAvailable;
  } catch (err) {
    hfAvailable = false;
    console.warn(`[AI Inference] HF API unreachable: ${err.message}. Using OpenRouter/Local fallback.`);
    return false;
  }
}

// Reset HF availability check every 10 minutes
setInterval(() => { hfAvailable = null; }, 10 * 60 * 1000);

export async function classifySingleBlock(text, proMode = false) {
  const modelName = proMode ? MODELS.pro : MODELS.standard;
  const url = `${HF_API_BASE}/${modelName}`;
  const truncatedText = text.split(/\s+/).slice(0, 500).join(' ');

  try {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 8000);

    const response = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ inputs: truncatedText }),
      signal: controller.signal
    });

    clearTimeout(timeout);

    if (response.status === 503) {
      console.warn(`[AI Inference] HF model is loading (503).`);
      return { aiProbability: null, source: 'hf_loading', model: modelName.split('/').pop() };
    }

    if (!response.ok) {
      throw new Error(`HF returned status ${response.status}`);
    }

    const result = await response.json();
    if (Array.isArray(result) && Array.isArray(result[0])) {
      const predictions = result[0];
      let aiProb = 0;
      
      if (modelName.includes('chatgpt-detector-roberta')) {
        const chatgpt = predictions.find(p => p.label === 'LABEL_1');
        aiProb = chatgpt ? chatgpt.score * 100 : 0;
      } else {
        const fake = predictions.find(p => p.label === 'Fake');
        aiProb = fake ? fake.score * 100 : 0;
      }
      return { aiProbability: aiProb, source: 'huggingface_api', model: modelName.split('/').pop() };
    }
    
    throw new Error('Invalid predictions structure from Hugging Face');
  } catch (err) {
    console.warn(`[AI Inference] HF error: ${err.message}`);
    return { aiProbability: null, source: 'hf_unavailable', model: modelName.split('/').pop() };
  }
}

function classifyBlockLocally(text) {
  const result = analyzeTextLocally(text);
  return {
    aiProbability: result.aiProbability || 0,
    source: 'local_heuristic',
    model: 'OmniDetect-7metric'
  };
}

async function classifyBlockWithOpenRouter(text, proMode = false) {
  const apiKeys = await getKeys();
  if (apiKeys.length === 0) return null;

  const modelToUse = proMode ? 'google/gemini-2.5-pro-exp:free' : 'openrouter/free';
  const prompt = `Analyze the following text block and calculate the probability (0 to 100%) that it was generated by an AI model (like ChatGPT, Claude, Gemini, Llama, etc.).
AI texts are characterized by repetitive transition patterns, standard vocabulary distributions, neutral syntax structures, and generic statements.

Text block to analyze: "${text.replace(/"/g, '\\"')}"

Respond with ONLY a valid raw JSON object. Do not include markdown code block formatting (no \`\`\`json). The JSON must have exactly these keys:
{
  "aiProbability": number,
  "reason": "short explanation of detection signals found"
}`;

  for (let i = 0; i < apiKeys.length; i++) {
    const apiKey = apiKeys[i];
    try {
      console.log(`[AI Inference failover] Trying OpenRouter block classifier with key index ${i}...`);
      const controller = new AbortController();
      const timeout = setTimeout(() => controller.abort(), 8000);

      const response = await fetch('https://openrouter.ai/api/v1/chat/completions', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${apiKey}`,
          'Content-Type': 'application/json',
          'HTTP-Referer': 'http://localhost:5173',
          'X-Title': 'OmniDetect AI'
        },
        body: JSON.stringify({
          model: modelToUse,
          messages: [{ role: 'user', content: prompt }],
          response_format: { type: 'json_object' }
        }),
        signal: controller.signal
      });
      clearTimeout(timeout);

      if (!response.ok) continue;

      const data = await response.json();
      const content = data.choices?.[0]?.message?.content?.trim();
      if (!content) continue;

      const parsed = JSON.parse(content);
      return {
        aiProbability: typeof parsed.aiProbability === 'number' ? parsed.aiProbability : null,
        source: `openrouter_ai (${parsed.reason || 'linguistic audit'})`,
        model: modelToUse.split('/').pop()
      };
    } catch (err) {
      console.warn(`[AI Inference failover] OpenRouter failed for key index ${i}:`, err.message);
    }
  }
  return null;
}

export async function classifyBlocks(blocks, proMode = false, fastCheck = false, onProgress = null) {
  const result = blocks.map(block => ({ ...block }));

  let isFast = fastCheck;
  let progressCallback = onProgress;
  if (typeof fastCheck === 'function') {
    progressCallback = fastCheck;
    isFast = false;
  }

  const processable = [];
  result.forEach((block, idx) => {
    if (!block.exclude) {
      processable.push(idx);
    } else {
      block.aiProbability = null;
      block.source = 'excluded';
      block.model = null;
    }
  });

  const total = processable.length;
  console.log(`[AI Inference] Processing ${total} blocks (${blocks.length - total} excluded)...`);
  if (total === 0) return result;

  if (isFast) {
    console.log(`[AI Inference] Fast Check Mode active.`);
    let processed = 0;
    for (const idx of processable) {
      const local = classifyBlockLocally(result[idx].text);
      result[idx].aiProbability = local.aiProbability;
      result[idx].source = local.source;
      result[idx].model = local.model;
      processed++;
      if (progressCallback) {
        progressCallback({
          current: processed,
          total,
          stage: 'inference',
          percent: Math.round((processed / total) * 100)
        });
      }
    }
    return result;
  }

  if (progressCallback) progressCallback({ current: 0, total, stage: 'inference', percent: 0 });
  const canUseHf = await testHfConnectivity();

  if (canUseHf) {
    console.log(`[AI Inference] Processing via Hugging Face API...`);
    const BATCH_SIZE = 5;
    let processed = 0;

    for (let i = 0; i < processable.length; i += BATCH_SIZE) {
      const batch = processable.slice(i, i + BATCH_SIZE);
      const batchResults = await Promise.all(
        batch.map(idx => classifySingleBlock(result[idx].text, proMode))
      );

      for (let j = 0; j < batch.length; j++) {
        const idx = batch[j];
        const res = batchResults[j];
        
        if (res.aiProbability === null) {
          const orRes = await classifyBlockWithOpenRouter(result[idx].text, proMode);
          if (orRes) {
            result[idx].aiProbability = orRes.aiProbability;
            result[idx].source = orRes.source;
            result[idx].model = orRes.model;
          } else {
            const local = classifyBlockLocally(result[idx].text);
            result[idx].aiProbability = local.aiProbability;
            result[idx].source = local.source;
            result[idx].model = local.model;
          }
        } else {
          result[idx].aiProbability = res.aiProbability;
          result[idx].source = res.source;
          result[idx].model = res.model;
        }
      }

      processed += batch.length;
      if (progressCallback) {
        progressCallback({ current: processed, total, stage: 'inference', percent: Math.round((processed / total) * 100) });
      }

      if (i + BATCH_SIZE < processable.length) {
        await new Promise(r => setTimeout(r, 200));
      }
    }
  } else {
    const orKeys = await getKeys();
    if (orKeys.length > 0) {
      console.log(`[AI Inference] HF down — Using OpenRouter AI models...`);
      let processed = 0;
      for (const idx of processable) {
        const orRes = await classifyBlockWithOpenRouter(result[idx].text, proMode);
        if (orRes) {
          result[idx].aiProbability = orRes.aiProbability;
          result[idx].source = orRes.source;
          result[idx].model = orRes.model;
        } else {
          const local = classifyBlockLocally(result[idx].text);
          result[idx].aiProbability = local.aiProbability;
          result[idx].source = local.source;
          result[idx].model = local.model;
        }
        processed++;
        if (progressCallback) {
          progressCallback({ current: processed, total, stage: 'inference', percent: Math.round((processed / total) * 100) });
        }
      }
    } else {
      console.log(`[AI Inference] HF & OpenRouter both unavailable — using local heuristics...`);
      let processed = 0;
      for (const idx of processable) {
        const local = classifyBlockLocally(result[idx].text);
        result[idx].aiProbability = local.aiProbability;
        result[idx].source = local.source;
        result[idx].model = local.model;
        processed++;
        if (progressCallback && processed % 5 === 0) {
          progressCallback({ current: processed, total, stage: 'inference', percent: Math.round((processed / total) * 100) });
        }
      }
      if (progressCallback) progressCallback({ current: total, total, stage: 'inference', percent: 100 });
    }
  }

  return result;
}

export function calculateSimilarityIndex(scoredBlocks) {
  const activeBlocks = scoredBlocks.filter(b => !b.exclude && b.aiProbability !== null);
  if (activeBlocks.length === 0) return 0;

  const totalWords = activeBlocks.reduce((sum, b) => sum + (b.wordCount || 1), 0);
  const weightedSum = activeBlocks.reduce((sum, b) => sum + (b.aiProbability * (b.wordCount || 1)), 0);

  return Math.round(weightedSum / totalWords);
}
