/**
 * openRouterService.js — Client-side OpenRouter integration.
 * Triggers rotating free models on OpenRouter for audits, text humanization, and metadata.
 */

import { getKeys } from './keyManager.js';

export async function auditTextWithAI(text, metrics, proMode = false) {
  const apiKeys = await getKeys();
  if (apiKeys.length === 0) return null;

  let prompt = '';
  let modelToUse = 'openrouter/free';

  if (proMode) {
    modelToUse = 'google/gemini-2.5-pro-exp:free';
    prompt = `You are an elite forensic linguist. Perform a Deep Audit on this text sample.
Text Sample: "${text.substring(0, 1500)}"
Metrics: Total Words: ${metrics.wordsCount || metrics.totalWords} | AI Probability: ${metrics.aiProbability}% | Flagged Buzzwords: ${metrics.flaggedWordsCount || 0} | Avg Word Length: ${metrics.avgWordLength || 5} | Burstiness: ${metrics.burstiness || 'Unknown'}

Generate a comprehensive forensic Markdown report with EXACTLY these 3 sections (use ## headers):
## 1. Where AI Was Used
Identify specific phrasing, unnatural transitions, mechanical structures, or flagged buzzwords that indicate AI generation.
## 2. Detection Methodology
Explain the linguistic flaws (e.g. low burstiness, predictability, low Shannon entropy) that exposed it.
## 3. Predicted AI Model
State which AI model likely generated this (e.g. ChatGPT/GPT-4, Claude 3, Gemini, etc.) and explain why based on its signature writing style and vocabulary.`;
  } else {
    prompt = `You are a forensic linguist. Review the text and its metrics to write a professional 3-sentence audit summary confirming if it is likely human-written, generated by ChatGPT/AI, or mixed:
- Text Sample (first 100 chars): "${text.substring(0, 100)}..."
- Total Words: ${metrics.wordsCount || metrics.totalWords}
- AI Probability: ${metrics.aiProbability}%
- Flagged Buzzwords count: ${metrics.flaggedWordsCount || 0}
- Average Word Length: ${metrics.avgWordLength || 5}
- Sentiment: ${metrics.sentiment || 'Neutral'}

Respond only with the 3-sentence summary in a professional, objective tone. Do not mention "as an AI" or any fluff.`;
  }

  for (let i = 0; i < apiKeys.length; i++) {
    const apiKey = apiKeys[i];
    try {
      console.log(`[OpenRouter Auditor] Sending text audit request with Key Index ${i}... (ProMode: ${proMode})`);
      const controller = new AbortController();
      const timeout = setTimeout(() => controller.abort(), 10000);
      const response = await fetch('https://openrouter.ai/api/v1/chat/completions', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${apiKey}`,
          'Content-Type': 'application/json',
          'HTTP-Referer': 'http://localhost:5173',
          'X-Title': 'OmniDetect AI'
        },
        body: JSON.stringify({
          model: modelToUse,
          messages: [
            { role: 'user', content: prompt }
          ]
        }),
        signal: controller.signal
      });
      clearTimeout(timeout);

      if (response.status === 429 || response.status === 401 || response.status === 403) {
        console.warn(`[OpenRouter Rotation] Key Index ${i} returned status ${response.status}. Rotating...`);
        continue;
      }

      if (!response.ok) {
        const errText = await response.text();
        console.warn(`[OpenRouter Rotation] Key Index ${i} failed: ${errText}. Rotating...`);
        continue;
      }

      const data = await response.json();
      return data.choices?.[0]?.message?.content?.trim() || 'No feedback received from AI Auditor.';
    } catch (err) {
      console.warn(`[OpenRouter Rotation] Key Index ${i} experienced network error: ${err.message}. Rotating...`);
    }
  }

  return 'AI Audit summary skipped: All available API keys failed to connect.';
}

export async function humanizeTextWithAI(text, proMode = false) {
  const apiKeys = await getKeys();
  
  const runLocalHumanize = (txt) => {
    let clean = txt;
    const replacements = {
      '\\b[Ff]urthermore\\b': 'Also',
      '\\b[Mm]oreover\\b': 'In addition',
      '\\b[Ii]n conclusion\\b': 'To wrap it up',
      '\\b[Cc]onsequently\\b': 'So',
      '\\b[Tt]estament to\\b': 'clear sign of',
      '\\b[Pp]ivotal\\b': 'key',
      '\\b[Rr]evolutionary\\b': 'cool',
      '\\b[Uu]tilize\\b': 'use',
      '\\b[Nn]otably\\b': 'Indeed',
      '\\b[Ss]ignificantly\\b': 'Largely',
      '\\b[Dd]iverse\\b': 'various',
      '\\b[Uu]nprecedented\\b': 'new and major',
      '\\b[Ff]oster\\b': 'help build',
      '\\b[Ee]xhibit\\b': 'show',
      '\\b[Dd]elineate\\b': 'show outline of',
      '\\b[Ii]nvaluable\\b': 'very helpful'
    };
    
    for (const [key, value] of Object.entries(replacements)) {
      clean = clean.replace(new RegExp(key, 'g'), value);
    }
    return {
      text: clean,
      method: 'Local Heuristic Synonym Replacer (Add OpenRouter key in settings for advanced LLM Humanizer)'
    };
  };

  if (apiKeys.length === 0) {
    return runLocalHumanize(text);
  }

  const modelToUse = proMode ? 'google/gemini-2.5-pro-exp:free' : 'openrouter/free';
  
  const systemPrompt = `You are a world-class professional editor and copywriter.
Your task is to rewrite the provided text so that it reads 100% naturally, like it was written by an expressive human.
Use these rules strictly:
1. Vary sentence length (mix short, punchy sentences with compound ones).
2. Avoid typical AI patterns (do not use words like "testament", "furthermore", "moreover", "delve", "tapestry", "beacon").
3. Write in an active, engaging voice.
4. Ensure the rewritten text passes AI detection tools (e.g. RoBERTa, GPTZero) with a 0% AI index score.
5. Maintain the EXACT original facts, meaning, and core argument.
6. Do NOT add any introductory explanation, conversational filler, or markdown commentary. Return ONLY the rewritten text itself.`;

  for (let i = 0; i < apiKeys.length; i++) {
    const apiKey = apiKeys[i];
    try {
      console.log(`[OpenRouter Humanizer] Sending humanize request with Key Index ${i}... (ProMode: ${proMode})`);
      const controller = new AbortController();
      const timeout = setTimeout(() => controller.abort(), 12000);
      
      const response = await fetch('https://openrouter.ai/api/v1/chat/completions', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${apiKey}`,
          'Content-Type': 'application/json',
          'HTTP-Referer': 'http://localhost:5173',
          'X-Title': 'OmniDetect AI'
        },
        body: JSON.stringify({
          model: modelToUse,
          messages: [
            { role: 'system', content: systemPrompt },
            { role: 'user', content: text }
          ],
          temperature: 0.85
        }),
        signal: controller.signal
      });
      clearTimeout(timeout);

      if (response.status === 429 || response.status === 401 || response.status === 403) {
        console.warn(`[OpenRouter Humanizer] Key Index ${i} returned status ${response.status}. Rotating...`);
        continue;
      }

      if (!response.ok) {
        const errText = await response.text();
        console.warn(`[OpenRouter Humanizer] Key Index ${i} failed: ${errText}. Rotating...`);
        continue;
      }

      const data = await response.json();
      const rewritten = data.choices?.[0]?.message?.content?.trim();
      if (rewritten) {
        return {
          text: rewritten,
          method: `OpenRouter AI Humanizer (Model: ${modelToUse})`
        };
      }
    } catch (err) {
      console.warn(`[OpenRouter Humanizer] Key Index ${i} failed: ${err.message}. Rotating...`);
    }
  }

  return runLocalHumanize(text);
}
