/**
 * Report Generator — Creates a full forensic PDF report summarizing scan results.
 * Uses pdf-lib to build a multi-page professional report.
 */
import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';

/**
 * Get color for AI probability display.
 */
function getProbColor(prob) {
  if (prob >= 70) return rgb(1, 0.27, 0.23);     // Red
  if (prob >= 50) return rgb(1, 0.62, 0.04);      // Orange
  return rgb(0.19, 0.82, 0.35);                   // Green
}

/**
 * Generate a comprehensive forensic scan report as a PDF.
 * @param {object} scanResult - The scan result data
 * @param {string} scanResult.scanId
 * @param {string} scanResult.fileName
 * @param {number} scanResult.aiSimilarityIndex
 * @param {Array} scanResult.blocks
 * @param {number} scanResult.totalBlocks
 * @param {number} scanResult.flaggedBlocks
 * @param {number} scanResult.excludedBlocks
 * @param {number} scanResult.totalWords
 * @param {string} scanResult.timestamp
 * @returns {Promise<Uint8Array>}
 */
export async function generateReport(scanResult) {
  const {
    scanId = 'N/A',
    fileName = 'Unknown',
    aiSimilarityIndex = 0,
    blocks = [],
    totalBlocks = 0,
    flaggedBlocks = 0,
    excludedBlocks = 0,
    totalWords = 0,
    timestamp = new Date().toISOString()
  } = scanResult;

  try {
    const pdfDoc = await PDFDocument.create();
    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    const PAGE_W = 595;  // A4 width in points
    const PAGE_H = 842;  // A4 height
    const MARGIN = 50;
    const CONTENT_W = PAGE_W - 2 * MARGIN;

    // ═══════════════════════════════════════════
    // PAGE 1: SUMMARY
    // ═══════════════════════════════════════════
    let page = pdfDoc.addPage([PAGE_W, PAGE_H]);
    let y = PAGE_H - MARGIN;

    // Title
    page.drawText('OmniDetect AI', { x: MARGIN, y, font: boldFont, size: 28, color: rgb(0, 0.8, 0.9) });
    y -= 30;
    page.drawText('Forensic Scan Report', { x: MARGIN, y, font: boldFont, size: 18, color: rgb(0.7, 0.7, 0.7) });
    y -= 40;

    // Divider line
    page.drawLine({ start: { x: MARGIN, y }, end: { x: PAGE_W - MARGIN, y }, thickness: 1, color: rgb(0.3, 0.3, 0.3) });
    y -= 30;

    // File info
    const infoLines = [
      ['File:', fileName],
      ['Scan ID:', scanId],
      ['Date:', new Date(timestamp).toLocaleString()],
      ['Total Words:', totalWords.toLocaleString()],
    ];

    for (const [label, value] of infoLines) {
      page.drawText(label, { x: MARGIN, y, font: boldFont, size: 11, color: rgb(0.6, 0.6, 0.6) });
      page.drawText(String(value), { x: MARGIN + 100, y, font, size: 11, color: rgb(1, 1, 1) });
      y -= 22;
    }

    y -= 20;

    // AI Similarity Index (large)
    page.drawText('AI Similarity Index', { x: MARGIN, y, font: boldFont, size: 14, color: rgb(0.7, 0.7, 0.7) });
    y -= 45;
    const indexColor = getProbColor(aiSimilarityIndex);
    page.drawText(`${aiSimilarityIndex.toFixed(1)}%`, { x: MARGIN, y, font: boldFont, size: 48, color: indexColor });
    y -= 50;

    // Stats boxes
    const stats = [
      { label: 'Total Blocks', value: totalBlocks },
      { label: 'Flagged Blocks', value: flaggedBlocks },
      { label: 'Excluded Blocks', value: excludedBlocks },
      { label: 'Clean Blocks', value: totalBlocks - flaggedBlocks - excludedBlocks },
    ];

    const boxW = CONTENT_W / 4 - 8;
    stats.forEach((stat, i) => {
      const bx = MARGIN + i * (boxW + 10);
      // Box background
      page.drawRectangle({ x: bx, y: y - 10, width: boxW, height: 50, color: rgb(0.1, 0.1, 0.12), borderWidth: 1, borderColor: rgb(0.2, 0.2, 0.25) });
      page.drawText(String(stat.value), { x: bx + 12, y: y + 20, font: boldFont, size: 18, color: rgb(1, 1, 1) });
      page.drawText(stat.label, { x: bx + 12, y: y + 2, font, size: 8, color: rgb(0.5, 0.5, 0.5) });
    });

    y -= 80;

    // Verdict
    let verdict = 'Likely Human';
    let verdictColor = rgb(0.19, 0.82, 0.35);
    if (aiSimilarityIndex >= 70) { verdict = 'Likely AI-Generated'; verdictColor = rgb(1, 0.27, 0.23); }
    else if (aiSimilarityIndex >= 40) { verdict = 'Mixed / Suspect'; verdictColor = rgb(1, 0.62, 0.04); }

    page.drawText('Verdict:', { x: MARGIN, y, font: boldFont, size: 13, color: rgb(0.6, 0.6, 0.6) });
    page.drawText(verdict, { x: MARGIN + 70, y, font: boldFont, size: 13, color: verdictColor });

    // Footer
    page.drawText('Generated by OmniDetect AI Forensic Auditor', { x: MARGIN, y: 30, font, size: 8, color: rgb(0.4, 0.4, 0.4) });

    // ═══════════════════════════════════════════
    // PAGE 2+: BLOCK DETAILS TABLE
    // ═══════════════════════════════════════════
    const ROWS_PER_PAGE = 25;
    const ROW_HEIGHT = 24;
    const COL_X = { num: MARGIN, text: MARGIN + 40, prob: MARGIN + 370, status: MARGIN + 430 };

    for (let pageStart = 0; pageStart < blocks.length; pageStart += ROWS_PER_PAGE) {
      page = pdfDoc.addPage([PAGE_W, PAGE_H]);
      y = PAGE_H - MARGIN;

      // Page header
      page.drawText('Block Analysis Details', { x: MARGIN, y, font: boldFont, size: 16, color: rgb(0, 0.8, 0.9) });
      y -= 30;

      // Column headers
      page.drawText('#', { x: COL_X.num, y, font: boldFont, size: 9, color: rgb(0.5, 0.5, 0.5) });
      page.drawText('Text Preview', { x: COL_X.text, y, font: boldFont, size: 9, color: rgb(0.5, 0.5, 0.5) });
      page.drawText('AI %', { x: COL_X.prob, y, font: boldFont, size: 9, color: rgb(0.5, 0.5, 0.5) });
      page.drawText('Status', { x: COL_X.status, y, font: boldFont, size: 9, color: rgb(0.5, 0.5, 0.5) });
      y -= 15;
      page.drawLine({ start: { x: MARGIN, y }, end: { x: PAGE_W - MARGIN, y }, thickness: 0.5, color: rgb(0.25, 0.25, 0.25) });
      y -= ROW_HEIGHT;

      const pageEnd = Math.min(pageStart + ROWS_PER_PAGE, blocks.length);

      for (let i = pageStart; i < pageEnd; i++) {
        const block = blocks[i];
        const prob = block.aiProbability;
        const probStr = prob !== null && prob !== undefined ? `${prob.toFixed(1)}%` : '—';

        let status = 'Clean';
        let statusColor = rgb(0.19, 0.82, 0.35);
        if (block.exclude) {
          status = block.excludeReason || 'Excluded';
          statusColor = rgb(0.5, 0.5, 0.5);
        } else if (prob !== null && prob >= 50) {
          status = 'Flagged';
          statusColor = rgb(1, 0.27, 0.23);
        }

        // Block number
        page.drawText(String(block.blockIndex + 1), { x: COL_X.num, y, font, size: 9, color: rgb(0.6, 0.6, 0.6) });

        // Text preview (truncate to 60 chars)
        const preview = block.text.substring(0, 60).replace(/\n/g, ' ') + (block.text.length > 60 ? '...' : '');
        // Sanitize for pdf-lib (remove non-latin1 chars)
        const safePrev = preview.replace(/[^\x20-\x7E]/g, '');
        page.drawText(safePrev, { x: COL_X.text, y, font, size: 8, color: rgb(0.8, 0.8, 0.8) });

        // Probability
        const pColor = prob !== null ? getProbColor(prob) : rgb(0.4, 0.4, 0.4);
        page.drawText(probStr, { x: COL_X.prob, y, font: boldFont, size: 9, color: pColor });

        // Status
        page.drawText(status, { x: COL_X.status, y, font, size: 9, color: statusColor });

        y -= ROW_HEIGHT;
      }

      // Footer
      page.drawText('Generated by OmniDetect AI Forensic Auditor', { x: MARGIN, y: 30, font, size: 8, color: rgb(0.4, 0.4, 0.4) });
    }

    console.log(`[ReportGen] Generated ${pdfDoc.getPageCount()}-page report for scan ${scanId}.`);

    return await pdfDoc.save();

  } catch (err) {
    console.error(`[ReportGen] Error generating report: ${err.message}`);
    throw err;
  }
}
